### ISSUE TITLE
End switch for lock command

### ISSUE THREAD

**Issue by c0ffein** [section77/nerdschloss#2]
Make an end switch on top of the door to get the current door state
-> If open don't lock the door

**Comment by sysdef** [comment]
Steps:
* design and print holder and bumper
* montage
* wiring up
* code change
* testing

**Comment by sysdef** [comment]
- [ ] design and print holder and bumper
- [ ] montage
- [ ] wiring up
- [ ] code change
- [ ] testing

**Comment by sportfloh** [comment]
Already solved by @bruder-jo
